 #TODO：druid连接池数据配置信息！！
 spring:
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource #使用druid连按池
    #username:账号#如果你springboot2整合druid连接池!使用此信息配置账号和password:
     druid:
      url: jdbc:mysql://localhost:3306/bookmanagesys
      username: root
      password: newbee
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化时建立物理连接的个数
      initial-size: 5
      #连接池的最小空闲数量
      min-idle: 5
      #连接池最大连接数量
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效,
      test-while idle: true
      #既作为检测的间隔时间又作为testwhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      #用来检测数据库连接是否有效的sql必须是一个查询语句(oracle中为select1 from dual)
      validation-query: select1
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #是否缓存preparedstatement，也就是PSCache,PScache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      #要启用PSCache，必须配置大于0，当大于@时，p0olPreparedstatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: -1
      #合并多个Dru1dDataSource的监控数据
      use-global-data-source-stat: true